import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Sidebar} from "@/components/layout/SideBar";
import {Header} from "@/components/layout/Header";
import {LoadingWrapper} from "@/components/layout/LoadingWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 flex min-h-screen`}
      >
      <Sidebar />
      <div className="flex-1 flex flex-col">
        <Header />
        <LoadingWrapper>{children}</LoadingWrapper>
      </div>
      </body>
    </html>
  );
}
